name: Build docker image

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compute short SHA
      run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    - name: Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: coreos-rpi-efi-extras
        tags: |
          ghcr.io/nickcmaynard/coreos-rpi-efi-extras:latest 
          ghcr.io/nickcmaynard/coreos-rpi-efi-extras:${{GITHUB_REF_NAME}}
          ghcr.io/nickcmaynard/coreos-rpi-efi-extras:sha-${{SHORT_SHA}}
        containerfiles: |
          ./Containerfile
        platforms: linux/amd64
        context: .

    - name: Push to GHCR
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
