name: Build releases

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    strategy:
      matrix: 
        release: [36, 37, 38, 39]
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nickcmaynard/coreos-rpi-efi-extras:latest
      volumes:
        - ${{ github.workspace }}:/output
    steps:
      - name: Run build process
        run: RELEASE=${{ matrix.release }} /app/build.sh
      - name: Upload artifact to release
        uses: actions/upload-artifact@v3
        with:
          name: release_${{ matrix.release }}
          path: ${{ github.workspace }}/coreos-rpi-efi-extras_*.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v3
      - name: Get current date
        id: date
        run: echo "name=date::$(date +"%Y-%m-%d_%H-%M") >> $GITHUB_OUTPUT"
      - name: Upload the release files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly_build_${{ steps.date.outputs.date }}
          files: ${{ github.workspace }}/**/coreos-rpi-efi-extras_*.zip
      - name: Delete old nightly releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 7
          delete_tag_pattern: nightly_build
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
