name: Build releases

# Controls when the workflow will run
on:
  workflow_dispatch:
  registry_package:
    types: [published]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nickcmaynard/coreos-rpi-efi-extras:latest
      volumes:
        - ${{ github.workspace }}:/output
    steps:
      - name: Run Fedora 35 build process
        run: RELEASE=35 /app/build.sh
      - name: Run Fedora 36 build process
        run: RELEASE=36 /app/build.sh
      - name: Run Fedora 37 build process
        run: RELEASE=37 /app/build.sh
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +"%Y-%m-%d_%H-%M")"
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Upload the release files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly_build_${{ steps.date.outputs.date }}
          files: ${{ github.workspace }}/coreos-rpi-efi-extras_*.zip
      - name: Delete old nightly releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 7
          delete_tag_pattern: nightly_build
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}